# Generated by Django 3.0.4 on 2020-03-20 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeek', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='id',
            field=models.URLField(primary_key=True, serialize=False),
        ),
    ]
