version: '3'
services:
  frontend:
    build: recipeek
    image: recipeek_react
    stdin_open: true
    ports: 
    - '3000:3000'
    depends_on: 
      - backend
  backend:
    build: rpserver
    image: recipeek_django
    hostname: backend
    ports:
    - '8000:8000'
  scrapers:
    build: scraper
    image: scrapers  
    depends_on:
     - backend
networks: 
  default:
    external: 
      name: 'recipeek'

    