version: '3'
services:
  frontend:
    build: recipeek
    image: recipeek_react
    ports: 
    - '3000:80'
    depends_on: 
      - backend
  backend:
    build: rpserver
    image: recipeek_django
    hostname: backend
    ports:
    - '8000:8000'
    env_file: .env
  scrapers:
    build: scraper
    image: scrapers 
    env_file: .env
    depends_on:
     - backend

networks: 
  default:
    external: 
      name: 'recipeek'

    