version: '3'
services:
  frontend:
    build: recipeek
    image: recipeek_react
    ports: 
    - '3000:3000'
    depends_on: 
      - backend
  backend:
    build: rpserver
    image: recipeek_django
    ports:
    - '8000:8000'
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
networks: 
  default:

    