FROM python:3.7-alpine

COPY . /app
WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apk update && \
    apk add --virtual build-deps gcc python-dev musl-dev && \
    apk add postgresql-dev

RUN pip install -r requirements.txt

#RUN python manage.py makemigrations
#RUN python manage.py migrate

EXPOSE 8000

ENTRYPOINT ["python"]
CMD ["manage.py", "runserver","0.0.0.0:8000"]